services:
  app:
    image: ghcr.io/jmorton95/clientbooking_qadtsl6:${GIT_COMMIT_HASH:-latest}
    environment:
      - DatabaseSettings__Host=db
      - DatabaseSettings__Port=5432
      - DatabaseSettings__Database=client_booking_staging
      - DatabaseSettings__Username=postgres
      - DatabaseSettings__Password=${DB_PASSWORD}
      - ConfigurationSettings__AuditLogPassword=${AUDIT_LOG_PASSWORD}
    deploy:
      update_config:
        order: start-first
    depends_on:
      - db
    networks:
      - staging-public

  db:
    image: postgres:18.1
    user: postgres
    volumes:
      - staging-database-data:/var/lib/postgresql
    secrets:
      - db-password
    environment:
      POSTGRES_DB: client_booking_staging
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - traefik-public
      - staging-internal

volumes:
  staging-database-data:

secrets:
  db-password:
    external: true

networks:
  staging-internal:
  traefik-public:
    external: true
